name: employee_info
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.7.1
  flutter_slidable: ^4.0.0
  uuid: ^4.4.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  connectivity_plus: ^6.1.2
  dropdown_button2: ^2.3.9
  table_calendar: ^3.2.0
  fluttertoast: ^8.2.11
  lottie: ^3.3.1
  hive: ^2.2.3
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto/static/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/static/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/static/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/static/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/static/Roboto-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/static/Roboto-Black.ttf
          weight: 800

  assets:
    - assets/
    - assets/lottie/misc_module/
    - assets/images/
    - assets/svg/










  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
